// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResearcherApiPrototype_1;

#nullable disable

namespace ResearcherApiPrototype_1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251201120321_third")]
    partial class third
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResearcherApiPrototype_1.Models.ControlBlockInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlcIpAdress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StaticObjectInfoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StaticObjectInfoId");

                    b.ToTable("ControlBlocks");
                });

            modelBuilder.Entity("ResearcherApiPrototype_1.Models.HardwareCharacteristic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HardwareId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HardwareId");

                    b.ToTable("Characteristics");
                });

            modelBuilder.Entity("ResearcherApiPrototype_1.Models.HardwareInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ControlBlockId")
                        .HasColumnType("integer");

                    b.Property<string>("DeveloperName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OpcDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ControlBlockId");

                    b.ToTable("Hardwares");
                });

            modelBuilder.Entity("ResearcherApiPrototype_1.Models.NodeIndicates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Indicates")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NodeInfoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NodeInfoId");

                    b.ToTable("NodesIndicates");
                });

            modelBuilder.Entity("ResearcherApiPrototype_1.Models.NodeInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HardwareId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCommand")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsValue")
                        .HasColumnType("boolean");

                    b.Property<string>("Mesurement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlcNodeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HardwareId");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("ResearcherApiPrototype_1.Models.StaticObjectInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GeneralContractorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperatingOrganization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ProjectEfficiency")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("StaticObjectInfos");
                });

            modelBuilder.Entity("ResearcherApiPrototype_1.Models.ControlBlockInfo", b =>
                {
                    b.HasOne("ResearcherApiPrototype_1.Models.StaticObjectInfo", "StaticObjectInfo")
                        .WithMany("ControlBlocks")
                        .HasForeignKey("StaticObjectInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaticObjectInfo");
                });

            modelBuilder.Entity("ResearcherApiPrototype_1.Models.HardwareCharacteristic", b =>
                {
                    b.HasOne("ResearcherApiPrototype_1.Models.HardwareInfo", "Hardware")
                        .WithMany("Characteristics")
                        .HasForeignKey("HardwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hardware");
                });

            modelBuilder.Entity("ResearcherApiPrototype_1.Models.HardwareInfo", b =>
                {
                    b.HasOne("ResearcherApiPrototype_1.Models.ControlBlockInfo", "ControlBlock")
                        .WithMany("HardwareInfo")
                        .HasForeignKey("ControlBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ControlBlock");
                });

            modelBuilder.Entity("ResearcherApiPrototype_1.Models.NodeIndicates", b =>
                {
                    b.HasOne("ResearcherApiPrototype_1.Models.NodeInfo", "NodeInfo")
                        .WithMany("NodeIndicates")
                        .HasForeignKey("NodeInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NodeInfo");
                });

            modelBuilder.Entity("ResearcherApiPrototype_1.Models.NodeInfo", b =>
                {
                    b.HasOne("ResearcherApiPrototype_1.Models.HardwareInfo", "HardwareInfo")
                        .WithMany("NodeInfos")
                        .HasForeignKey("HardwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HardwareInfo");
                });

            modelBuilder.Entity("ResearcherApiPrototype_1.Models.ControlBlockInfo", b =>
                {
                    b.Navigation("HardwareInfo");
                });

            modelBuilder.Entity("ResearcherApiPrototype_1.Models.HardwareInfo", b =>
                {
                    b.Navigation("Characteristics");

                    b.Navigation("NodeInfos");
                });

            modelBuilder.Entity("ResearcherApiPrototype_1.Models.NodeInfo", b =>
                {
                    b.Navigation("NodeIndicates");
                });

            modelBuilder.Entity("ResearcherApiPrototype_1.Models.StaticObjectInfo", b =>
                {
                    b.Navigation("ControlBlocks");
                });
#pragma warning restore 612, 618
        }
    }
}
